### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by matyo91** [marcosh/lamphpda#30]
Hello,

As I can likely understand terms as `Applicative`, `Functor`, `SemiGroup` which are mathematical terms we can found on schema https://en.wikipedia.org/wiki/Monoid

I don't understand what are all terms and specially what is `Brand` and `HK1`.
So may be adding some documentation about mathematical terms on the project should help people understands the theorical concepts.

**Comment by marcosh** [comment]
There's also issue #7 regarding documentation

For the moment, the best reference for understanding the concepts is my blog.
In particular, regarding branded types and higher kinded types, you can take a look at
http://marcosh.github.io/post/2020/04/15/higher-kinded-types-php-issue.html and http://marcosh.github.io/post/2020/04/15/higher-kinded-types-php-solution.html

**Comment by matyo91** [comment]
Thanks. So I close the issue as there is already one open and as the issue will stay referenced to #7 !
