### ISSUE TITLE
Converting `list<Maybe<T>>` to `Maybe<list<T>>`

### ISSUE THREAD

**Issue by someniatko** [marcosh/lamphpda#42]
Inspired by `Promise:all()` from JavaScript.

Could a function which takes list of Maybes, and if ALL of them are `just`, returns a single Maybe with list of wrapped values, however if ANY of them is `nothing`, returns `Maybe::nothing`, be of any use? 
Or maybe it already exists in some more generic form?

**Comment by marcosh** [comment]
Such a function is already present in the library in the form of [`sequence`](https://github.com/marcosh/lamphpda/blob/5b4cddbed0ede309a6fe39a561efed7f100a5dd2/src/Typeclass/Extra/ExtraTraversable.php#L37). I would recommend to take a look also at the [Haskell definition](https://hackage.haskell.org/package/base-4.16.2.0/docs/Prelude.html#v:sequenceA) and the `Traversable` typeclass

**Comment by someniatko** [comment]
Thank you!
